# Generated by Django 2.2.2 on 2020-02-19 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0002_auto_20200213_1452'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ThreadEdit',
        ),
    ]
