# Generated by Django 2.2.2 on 2020-02-19 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0005_auto_20200218_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='deleted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='threadreply',
            name='deleted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
