# Generated by Django 2.2.2 on 2020-02-16 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ip_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registertoken',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
